config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'

  resources :boards do
    resources :comments, only: [:new, :create]
    
    resource :like, only: [:create, :destroy]

   
  end
  resource :profile, only: [:show, :edit, :update]
  #indexは複数を表示するものだからrouteは作られない

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id          :bigint           not null, primary key
#  description :text             not null
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
class Board < ApplicationRecord
  has_one_attached :eyecatch

  validates :name, presence: true
  validates :name, length: { minimum: 3 }

  validates :description, presence: true
  validates :description, length: {minimum: 5 }

  has_many :comments, dependent:  :destroy
  has_many :likes, dependent:  :destroy
  belongs_to :user

  def likes_count
    likes.count
  end

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id          :bigint           not null, primary key
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  board_id    :bigint           not null
#
# Indexes
#
#  index_comments_on_board_id  (board_id)
#
class Comment < ApplicationRecord
  belongs_to :board
  validates :description, presence: true
end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_likes_on_board_id  (board_id)
#  index_likes_on_user_id   (user_id)
#
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :board
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id           :bigint           not null, primary key
#  birthday     :date
#  gender       :integer
#  introduction :text
#  nickname     :string
#  subscribed   :boolean          default(FALSE)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
  enum gender: { male: 0, female: 1, other: 2 }
  belongs_to :user
  has_one_attached :avatar

  def age
    return '不明' unless birthday.present?
    years = Time.zone.now.year - birthday.year
    days = Time.zone.now.yday - birthday.yday

    if days < 0
      "#{years - 1}歳"
    else
      "#{years}歳"
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :boards, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one :profile, dependent: :destroy
  delegate :birthday, :age, :gender, to: :profile, allow_nil: true

  def has_written?(board)
    boards.exists?(id: board.id)
  end

  def has_liked?(board)
    likes.exists?(board_id: board.id)
  end

  def display_name
    profile&.nickname || self.email.split('@').first
    #if profile && profile.nickname
     # profile.nickname 
    #else
     # self.email.split('@').first
    #end
    # spritの役割 => ['yamada0303', 'gmail.com'
  end

  

  def prepare_profile
    profile || build_profile
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @boards = Board.all
  end

  def show
    @board = Board.find(params[:id])
    @comments = @board.comments
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to board_path(@board), notice: 'つぶやけた！'
    else
      flash.now[:error] = 'つぶやけなかった'
      render :new
    end
  end

  def edit
    @board = current_user.boards.find(params[:id])
  end

  def update
    @board = current_user.boards.find(params[:id])
    if @board.update(board_params)
      redirect_to board_path(@board), notice: '変更したよ'
    else
      flash.now[:error] = '変更できなかったよ'
      render :edit
    end
  end

  def destroy
    board = current_user.boards.find(params[:id])
    board.destroy!
    redirect_to root_path, notice: 'つぶやきを消したよ'
  end



  private 
  def board_params
    params.require(:board).permit(:name, :description, :eyecatch)
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    board = Board.find(params[:board_id])
    @comment = board.comments.build
  end

  def create
    board = Board.find(params[:board_id])
    @comment = board.comments.build(comment_params)
    if @comment.save
      redirect_to board_path(board), notice: 'コメントしたよ'
    else
      flash.now[:error] = 'コメントできなかった'
      render :new
    end
  end


  private
  def comment_params
    params.require(:comment).permit(:description)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    board = Board.find(params[:board_id])
    board.likes.create!(user_id: current_user.id)
    redirect_to board_path(board)
  end

  def destroy
    board = Board.find(params[:board_id])
    like =  board.likes.find_by!(user_id: current_user.id)
    like.destroy!
    redirect_to board_path(board)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user! #ログインしてないとこれらできない
  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.prepare_profile     
  end

  def update
    @profile = current_user.prepare_profile
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: '更新したよ'
    else
      flash.now[:error] = '更新できなかった'
      render :edit
    end
  end

  private

  def profile_params
    params.require(:profile).permit(
      :nickname,
      :introduction,
      :gender,
      :birthday,
      :subscribed,
      :avatar
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/edit.html.haml
.container
  - @board.errors.full_messages.each do |message|
    %li.error_message= message
  = form_with(model: @board, url: board_path(@board), method: 'put', local: true) do |f|
    %div.form_area
      %div
        = f.label :name, 'タイトル',class: 'form_text'
      %div
        = f.text_field :name, class: 'form_title'
      %div
        = f.label :description, '呟きたいこと',class: 'form_text'
      %div
        = f.text_area :description, class: 'form_description'
      = f.submit '投稿する', class: 'btn_prymary'

app/views/boards/index.html.haml
- if user_signed_in?
  %header.header_second
    = image_tag 'header.png', class: 'header_cat'
    %p.header_pageTitle_second PRAISE
    %p.header_text みんなで褒めあおう！ 
    今日もありがとう
    君がいてくれてよかった
  -@boards.each do |board|
    = link_to board_path(id: board.id) do
      .card
        .card_detail
          = image_tag board.user.avatar_image
          %div
            %p= board.user.display_name
            %p= I18n.l(board.created_at, format: :default)
        - if board.eyecatch.attached?
          .card_image
            = image_tag board.eyecatch
        .card_title
          = board.name
        .card_content
          .card_heart
            = image_tag 'heart.svg'          
            %span= board.likes_count
      = yield

app/views/boards/new.html.haml
.container
  - @board.errors.full_messages.each do |message|
    %li.error_message= message
  = form_with(model: @board, url: boards_path, method: 'post', local: true) do |f|
    %div.form_area
      %div
        = f.label :eyecatch, 'アイキャッチ'
      %div
        = f.file_field :eyecatch
      %div
        = f.label :name, 'タイトル',class: 'form_text'
      %div
        = f.text_field :name, class: 'form_title'
      %div
        = f.label :description, '呟きたいこと',class: 'form_text'
      %div
        = f.text_area :description, class: 'form_description'
      = f.submit '投稿する', class: 'btn_prymary'

app/views/boards/show.html.haml
.board
  - if @board.eyecatch.attached?
    .card_image
      = image_tag @board.eyecatch
  .board_detail
    = image_tag  @board.user.avatar_image
  %div
    %p= @board.user.display_name
    %p= I18n.l(@board.created_at, format: :default)
  - if user_signed_in? && current_user.has_written?(@board)
    .board_edit
      = link_to '編集する', edit_board_path(@board) 
    .board_edit
      = link_to '削除する', board_path(@board), data: { method: 'delete', confirm: '本当に削除しますか？'}
  %h1.board_title
    = @board.name  
  .board_content
    = @board.description
  - if user_signed_in?
    - if current_user.has_liked?(@board)
      .board_heart
        = link_to board_like_path(@board), data: { method: 'delete' } do
          = image_tag 'heart-active.svg'
    - else
      .board_heart
        = link_to board_like_path(@board), data: { method: 'post' } do
          = image_tag 'heart.svg'

.board_comment
  %h2 コメント一覧
  - @comments.each do |comment|
    .board_comment_text
      %p= comment.description

.container
  = link_to new_board_comment_path(@board) do
    .new_comment_button
      コメントをする

app/views/comments/new.html.haml
.container
  -@comment.errors.full_messages.each do |message|
    %li.error_message= message
  = form_with(model: @comment, url: board_comments_path(@comment.board), local: true) do |f|
    %div.form_area
      %div
        = f.label :description, 'なんてコメントする？',class: 'form_text'
      %div  
        = f.text_area :description, class: 'form_description'
      = f.submit 'コメントする',  class: 'btn_prymary'
        

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Praise
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css", :rel => "stylesheet"}/
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js", :type => "text/javascript"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js", :type => "text/javascript"}

  %body
    %header.header
      .header_logos
        - if !current_page?(root_path)
          =link_to :back do
            = image_tag 'back-button.svg', class: 'header_back_button'
      .header_pageTitle 
        = link_to 'P R A I S E', root_path
      - if user_signed_in?
        .dropdown
          = image_tag current_user.avatar_image, class: 'header_avatar dropbtn'
          .dropdown-content
            = link_to 'プロフィール', profile_path
            = link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete'}
      - else
        .dropdown
          = image_tag 'default-avatar.png', class: 'header_avatar dropbtn'
          .dropdown-content
            = link_to 'ログイン', new_user_session_path 
          
         
          
      - if user_signed_in?
        .container_menu
          .tabs
            .tabs_item.active
              .tabs_icon
                = image_tag 'article.png'
                新着記事
            .tabs_item
              .tabs_icon
                = image_tag 'mypage.png'
                タイムラ
            .tabs_item
              = link_to new_board_path do    
                .tabs_icon
                  = image_tag 'new.png'      
                  投稿
        - if flash.present?
          .flash
            - flash.each do |key, value|
              %div{:class => key}= value
    = yield

app/views/profiles/edit.html.haml
.container
  - @profile.errors.full_messages.each do |message|
    %li.error_message= message
  = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
    %div.form_area
      %div
        = f.label :avatar, 'アバター'
      %div
        = f.file_field :avatar
      %div
        = f.label :nickname, 'ハンドルネーム', class: 'form_text'
      %div
        = f.text_field :nickname,  class: 'form_title'
      %div
        = f.label :introduction, '自己紹介', class: 'form_text'
      %div
        = f.text_area :introduction ,class: 'form_introduction'
      %div
        = f.label :gender, '性別'
      %div
        = f.select :gender, Profile.genders.map { |k, v| [ I18n.t("enum.genders.#{k}"), k ] }, {}, { class: 'form_text' }
      %div 
        = f.label :birthday, '生年月日'
      %div
        = f.date_field :birthday, class: 'form_text'
      %div
        = f.label :subscribed, '通知を受け取る'
        = f.check_box :subscribed
      =f.submit '保存', class: 'btn_prymary'

app/views/profiles/show.html.haml
.profilePage
  .profile_user
    .profile_user_image
      = image_tag current_user.avatar_image
    .profile_content
      .profile_name
        #{current_user.display_name} (#{current_user.age} #{I18n.t("enum.genders.#{current_user.gender}")})
        .profile_edit_button
          = link_to 'edit', edit_profile_path
    .profile_user_introduction
      = current_user.profile&.introduction
      

  - current_user.boards.each do |board|
    = link_to board_path(id: board.id) do
      .card
        .card_detail
          = image_tag 'default-avatar.png'
          %div
            %p= board.user.display_name
            %p= I18n.l(board.created_at, format: :default)
        .card_image
          = image_tag 'sample.png'
        .card_title
          = board.name
        .card_content
          .card_heart
            = image_tag 'heart.svg'          
            %span 23